/**
 * Cigar Nexus graph data — 169 nodes, 330 links
 * Updated: P0–P3 Privada factory map cross-check (May 2026)
 */
var baseGraphData = {
            nodes: [
                { id: "myfather", name: "My Father", type: "brand", group: "family", country: "nicaragua", productLines: ["Le Bijou", "The Judge", "Le Grande", "Flor de las Antillas", "My Father Connecticut"], logo: "logos/myfather.png" },
                { id: "pepin", name: "Pepín García", type: "person", group: "family", country: "nicaragua", photo: "logos/pepingarcia.jpg" },
                { id: "tatuaje", name: "Tatuaje", type: "brand", group: "family", country: "nicaragua", productLines: ["Brown Label", "Black Label", "Havana VI", "Reserva", "Fausto", "Cojonú"], logo: "logos/tatuaje.png" },
                { id: "espinosa", name: "Espinosa Premium Cigars", type: "company", group: "family", country: "usa", productLines: ["601", "Murciélago", "Laranja", "Espinosa Habano", "Knuckle Sandwich"], logo: "logos/espinosa.webp" },
                { id: "erikespinosa", name: "Erik Espinosa", type: "person", group: "family", country: "usa", photo: "logos/erikespinosa.png" },
                { id: "guyfieri", name: "Guy Fieri", type: "person", group: "family", country: "usa", photo: "logos/guyfieri.jpg" },
                { id: "lazona", name: "La Zona (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "laranja", name: "Laranja Reserva", type: "brand", group: "family", country: "nicaragua", logo: "logos/laranja.webp" },
                { id: "espinosahabano", name: "Espinosa Habano", type: "brand", group: "family", country: "nicaragua" },
                { id: "crema", name: "Crema", type: "brand", group: "family", country: "nicaragua" },
                { id: "knucklesandwich", name: "Knuckle Sandwich", type: "brand", group: "family", country: "nicaragua", logo: "logos/knucklesandwich.jpg" },
                { id: "eobrands", name: "EO Brands (legacy)", type: "company", group: "family", country: "usa", logo: "logos/eobrands.png" },
                { id: "eddieortega", name: "Eddie Ortega", type: "person", group: "family", country: "usa", photo: "logos/eddieortega.webp" },
                { id: "sixzeroone", name: "601", type: "brand", group: "family", country: "nicaragua", logo: "logos/601.webp" },
                { id: "murcielago", name: "Murciélago", type: "brand", group: "family", country: "nicaragua", logo: "logos/murcielago.png" },
                { id: "ajfernandez", name: "A.J. Fernandez", type: "person", group: "family", country: "nicaragua", productLines: ["San Lotano", "New World", "Enclave", "Bellagio", "Last Call"], photo: "logos/ajfernandez.jpg" },
                { id: "sanlotano", name: "San Lotano Factory (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "padron", name: "Padrón", type: "brand", group: "family", country: "nicaragua", productLines: ["1964 Anniversary", "1926 Serie", "3000", "4000", "5000", "6000"], logo: "logos/padron.png" },
                { id: "joseopadron", name: "José Orlando Padrón", type: "person", group: "family", country: "usa", photo: "logos/joseorlandopadron.png" },
                { id: "jorgepadron", name: "Jorge Padrón", type: "person", group: "family", country: "usa", photo: "logos/jorgepadron.png" },
                { id: "orlandopadron", name: "Orlando Padrón", type: "person", group: "family", country: "usa", photo: "logos/orlandopadron.png" },
                { id: "tabacoscubanica", name: "Tabacos Cubanica (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "padron1964", name: "Padrón 1964 Anniversary", type: "brand", group: "family", country: "nicaragua", logo: "logos/padron1964.jpg" },
                { id: "padron1926", name: "Padrón Serie 1926", type: "brand", group: "family", country: "nicaragua", logo: "logos/padron1926.jpg" },
                { id: "davidoff", name: "Davidoff", type: "brand", group: "corporate", country: "dominican", productLines: ["Grand Cru", "Millennium", "Nicaragua", "Winston Churchill", "Late Hour"], logo: "logos/davidoff.png" },
                { id: "avo", name: "AVO", type: "brand", group: "corporate", country: "dominican", productLines: ["Classic", "Heritage", "Syncro", "XO", "Proper"], logo: "logos/avo.jpg" },
                { id: "griffins", name: "The Griffin's", type: "brand", group: "corporate", country: "dominican", productLines: ["Classic", "Vintage", "Escudo", "Naturale"], logo: "logos/thegriffins.jpg" },
                { id: "tabadom", name: "Tabadom (Villa González)", type: "factory", group: "corporate", country: "dominican" },
                { id: "oettinger", name: "Oettinger Davidoff", type: "company", group: "corporate", country: "switzerland", logo: "logos/oettingerdavidoff.svg" },
                { id: "arturo", name: "Arturo Fuente", type: "brand", group: "family", country: "dominican", productLines: ["OpusX", "Hemingway", "Don Carlos", "Flor Fina 8-5-8", "Añejo"], logo: "logos/arturofuente.png" },
                { id: "tabafuente", name: "Tabacalera A. Fuente", type: "factory", group: "family", country: "dominican" },
                { id: "opusx", name: "Fuente Fuente OpusX", type: "brand", group: "family", country: "dominican", logo: "logos/fuenteopusx.jpg" },
                { id: "jcnewman", name: "J.C. Newman", type: "brand", group: "family", country: "usa", logo: "logos/jcnewman.webp" },
                { id: "diamondcrown", name: "Diamond Crown", type: "brand", group: "family", country: "dominican", logo: "logos/diamondcrown.webp" },
                { id: "stg", name: "Scandinavian Tobacco Group (STG)", type: "company", group: "corporate", country: "denmark", logo: "logos/scandinavian.svg" },
                { id: "generalcigar", name: "General Cigar Co.", type: "company", group: "corporate", country: "usa", logo: "logos/generalcigar.jpg" },
                { id: "forged", name: "Forged Cigar Co.", type: "company", group: "corporate", country: "usa", logo: "logos/forgedcigarcompany.webp" },
                { id: "macanudo", name: "Macanudo", type: "brand", group: "corporate", country: "dominican", productLines: ["Cafe", "Vintage", "Cru Royale", "Inspirado", "Estate Reserve"], logo: "logos/macanudo.svg" },
                { id: "cao", name: "CAO", type: "brand", group: "corporate", country: "nicaragua", productLines: ["Brazilia", "Ecuador", "Flathead", "MX2", "Conquest"], logo: "logos/cao.jpg" },
                { id: "cohiba_nc", name: "Cohiba (Non-Cuban)", type: "brand", group: "corporate", country: "dominican", logo: "logos/cohiba.jpg" },
                { id: "partagas_nc", name: "Partagas (Non-Cuban)", type: "brand", group: "corporate", country: "dominican", logo: "logos/partagas.svg" },
                { id: "punch_nc", name: "Punch (Non-Cuban)", type: "brand", group: "corporate", country: "dominican", productLines: ["Punch", "Punch Signature", "Punch Deluxe"], logo: "logos/punch.jpg" },
                { id: "plasencia", name: "Plasencia Cigars", type: "company", group: "family", country: "nicaragua", productLines: ["Alma Fuerte", "Alma del Campo", "Alma del Fuego", "Cosecha 146", "1865"], logo: "logos/plasencia.svg" },
                { id: "nestorplasencia", name: "Nestor Plasencia Sr.", type: "person", group: "family", country: "nicaragua", photo: "logos/nestorplasenciasr.png" },
                { id: "nestorandres", name: "Nestor Andrés Plasencia", type: "person", group: "family", country: "nicaragua", photo: "logos/nestorandresplasencia.png" },
                { id: "plasenciaesteli", name: "Plasencia Estelí (The Cathedral)", type: "factory", group: "family", country: "nicaragua" },
                { id: "rockypatel", name: "Rocky Patel Premium Cigars", type: "company", group: "family", country: "usa", productLines: ["Decade", "Olde World", "Vintage 1990", "The Edge", "Sun Grown"], logo: "logos/rockypatel.webp" },
                { id: "nishpatel", name: "Nish Patel", type: "person", group: "family", country: "usa", photo: "logos/nishpatel.png" },
                { id: "tavicusa", name: "Tabacalera Villa Cuba (TaviCusa, Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "drewestate", name: "Drew Estate", type: "company", group: "family", country: "usa", productLines: ["Liga Privada", "Undercrown", "Herrera Estelí", "Acid", "MUWAT"], logo: "logos/drewestate.jpg" },
                { id: "jonathandrew", name: "Jonathan Drew (Sann)", type: "person", group: "family", country: "usa", photo: "logos/jonathandrewsann.jpg" },
                { id: "swisher", name: "Swisher International", type: "company", group: "corporate", country: "usa", logo: "logos/swisher.svg" },
                { id: "lagranfabrica", name: "La Gran Fábrica Drew Estate (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "cle", name: "CLE Cigar Company", type: "company", group: "family", country: "usa", productLines: ["Corojo", "Connecticut", "Cuarenta", "Plus", "Eiroa"], logo: "logos/cle.webp" },
                { id: "christianeiroa", name: "Christian Eiroa", type: "person", group: "family", country: "honduras", photo: "logos/christianeiroa.jpg" },
                { id: "eiroafamily", name: "Eiroa Family (Aladino)", type: "company", group: "family", country: "honduras", logo: "logos/aladinocigars.png" },
                { id: "eiroadanli", name: "CLE Factory (Danlí, Honduras)", type: "factory", group: "family", country: "honduras" },
                { id: "aganorsa", name: "Aganorsa Leaf", type: "company", group: "family", country: "nicaragua", logo: "logos/aganorsa.jpg" },
                { id: "maxfernandez", name: "Max Fernández Pujals", type: "person", group: "family", country: "nicaragua", photo: "logos/maxfernandezpujals.png" },
                { id: "tabsa", name: "TABSA (Aganorsa Factory, Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "foundation", name: "Foundation Cigar Company", type: "company", group: "family", country: "usa", productLines: ["The Tabernacle", "Olmec", "El Güegüense", "Guardian of the Farm"], logo: "logos/foundation.jpg" },
                { id: "nickmelillo", name: "Nick Melillo", type: "person", group: "family", country: "usa", photo: "logos/nickmelillo.png" },
                { id: "alecbradley", name: "Alec Bradley", type: "brand", group: "corporate", country: "honduras", productLines: ["Prensado", "Tempus", "Cigar of the Year", "Black Market", "Magic Toast"], logo: "logos/alecbradley.webp" },
                { id: "room101", name: "Room101", type: "brand", group: "corporate", country: "dominican", logo: "logos/room101.jpg" },
                { id: "warped", name: "Warped Cigars", type: "brand", group: "family", country: "usa", productLines: ["Corto", "Sarto", "Cloud Hopper", "Futuro", "Guardian", "El Oso"], logo: "logos/warped.svg" },
                { id: "kylegellis", name: "Kyle Gellis", type: "person", group: "family", country: "usa", photo: "logos/kylegellis.png" },
                { id: "nacsa", name: "NACSA (Estelí)", type: "factory", group: "family", country: "nicaragua", logo: "logos/nacsa.jpg" },
                { id: "oliva", name: "Oliva Cigar Co.", type: "company", group: "corporate", country: "nicaragua", productLines: ["Serie V", "Melanio", "Nub", "Cain", "V Melanio", "Serie G"], logo: "logos/oliva.webp" },
                { id: "fredvandermarliere", name: "Fred Vandermarliere", type: "person", group: "corporate", country: "belgium", photo: "logos/fredvandermarliere.jpg" },
                { id: "tabolisa", name: "Tabolisa (Oliva Estelí)", type: "factory", group: "corporate", country: "nicaragua" },
                { id: "perdomo", name: "Perdomo Cigars", type: "company", group: "family", country: "nicaragua", productLines: ["Reserve 10th Anniversary", "Lot 23", "Champagne", "Patrón", "20th Anniversary"], logo: "logos/perdomo.webp" },
                { id: "nickperdomo", name: "Nick Perdomo Jr.", type: "person", group: "family", country: "usa", photo: "logos/nickperdomojr.jpg" },
                { id: "perdomofactory", name: "Tabacalera Perdomo (El Monstro, Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "joya", name: "Joya de Nicaragua", type: "brand", group: "family", country: "nicaragua", productLines: ["Antaño 1970", "Clásico", "Cinco Décadas", "Joya Red", "Joya Silver"], logo: "logos/joya.png" },
                { id: "joyafactory", name: "Joya de Nicaragua Factory (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "alejandromartinez", name: "Alejandro Martínez Cuenca", type: "person", group: "family", country: "nicaragua", photo: "logos/alejandromartinezcuenca.png" },
                { id: "dunbarton", name: "Dunbarton Tobacco & Trust", type: "company", group: "family", country: "usa", productLines: ["Sobremesa", "Mi Querida", "Muestra de Saka", "Sin Compromiso", "Todos Los Días"], logo: "logos/dunbarton.webp" },
                { id: "stevesaka", name: "Steve Saka", type: "person", group: "family", country: "usa", photo: "logos/stevesaka.png" },
                { id: "sobremesa", name: "Sobremesa", type: "brand", group: "family", country: "nicaragua", logo: "logos/sobremesa.png" },
                { id: "illusione", name: "Illusione Cigars", type: "brand", group: "family", country: "usa", productLines: ["Original Document", "Singularé", "88", "CG4", "Epernay"], logo: "logos/illusione.jpg" },
                { id: "diongiolito", name: "Dion Giolito", type: "person", group: "family", country: "usa", photo: "logos/diongiolito.png" },
                { id: "viaje", name: "Viaje Cigars", type: "brand", group: "family", country: "usa", productLines: ["Exclusivo", "Double Ligero", "Placeres", "Oro", "Summerfest"], logo: "logos/viaje.jpg" },
                { id: "andrefarkas", name: "Andre Farkas", type: "person", group: "family", country: "usa", photo: "logos/andrefarkas.png" },
                { id: "hvc", name: "HVC Cigars", type: "company", group: "family", country: "nicaragua", productLines: ["Hot Cake", "Black Friday", "Edición Limitada", "Pan Caliente"], logo: "logos/hvc.webp" },
                { id: "reinierlorenzo", name: "Reinier Lorenzo", type: "person", group: "family", country: "nicaragua", photo: "logos/reinierlorenzo.jpg" },
                { id: "hvcfactory", name: "HVC Factory (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "rickrodriguez", name: "Rick Rodriguez", type: "person", group: "family", country: "usa", photo: "logos/rickrodriguez.png" },
                { id: "westtampa", name: "West Tampa Tobacco Co.", type: "brand", group: "family", country: "usa", productLines: ["White", "Black", "Red", "Attic Series", "Circle of Life", "Dark Time"], logo: "logos/westtampa.jpg" },
                { id: "garmendia", name: "Garmendia Cigars (Estelí)", type: "factory", group: "family", country: "nicaragua", logo: "logos/garmendia.png" },
                { id: "chantelleavitt", name: "Chantel Leavitt", type: "person", group: "family", country: "usa", photo: "logos/chantelleavitt.png" },
                { id: "belladamacigars", name: "Bella Dama Cigars", type: "brand", group: "family", country: "usa", productLines: ["The King", "Ace", "The Queen", "Flush", "Full House", "All-In", "Dealer's Choice"], logo: "logos/belladama.png" },
                { id: "tabacaleraaragon", name: "Tabacalera Aragon (Estelí)", type: "factory", group: "family", country: "nicaragua" },
                { id: "camacho", name: "Camacho", type: "brand", group: "corporate", country: "honduras", productLines: ["Corojo", "Connecticut", "Triple Maduro", "Broadleaf", "Ecuador"], logo: "logos/camacho.jpg" },
                { id: "zino", name: "Zino", type: "brand", group: "corporate", country: "honduras", productLines: ["Zino Platinum", "Zino Nicaragua", "Zino Honduras"], logo: "logos/zino.jpg" },
                { id: "laaromadecuba", name: "La Aroma de Cuba", type: "brand", group: "family", country: "nicaragua", productLines: ["Original", "Mi Amor", "Edición Especial", "Pasión", "Noblesse", "Connecticut"], logo: "logos/laaroma.svg" },
                { id: "sancristobal", name: "San Cristobal", type: "brand", group: "family", country: "nicaragua", productLines: ["Clasico", "Revelation", "Quintessence", "La Fuerza", "Paradiso"], logo: "logos/sancristobal.svg" },
                { id: "ashton", name: "Ashton", type: "brand", group: "corporate", country: "dominican", productLines: ["Classic", "Cabinet Selection", "Aged Maduro", "VSG", "ESG", "Symmetry"], logo: "logos/ashton.svg" },
                { id: "lure", name: "Lure Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["Corojo", "Habano", "Oscuro", "Maduro", "All-In"], logo: "logos/lure.png" },
                { id: "definition", name: "Definition Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["GEN 413", "919 Series", "Noir", "Conception", "The Pig"], logo: "logos/definition.png" },
                { id: "lagloriacubana", name: "La Gloria Cubana", type: "brand", group: "corporate", country: "dominican", productLines: ["Serie R", "Original", "Intención", "Los Gloriosos", "100 Años"], logo: "logos/lagloria.jpg" },
                { id: "domain", name: "Domain Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["Neutron", "Negentropy", "Entropy"], logo: "logos/domain.webp" },
                { id: "estebandisla", name: "Esteban Disla", type: "person", group: "family", country: "nicaragua", photo: "logos/estebandisla.png" },
                { id: "daniellance", name: "Daniel Lance", type: "person", group: "family", country: "usa", photo: "logos/daniellance.jpg" },
                { id: "familiadisla", name: "Tabacalera Familia Disla S.A.", type: "factory", group: "family", country: "nicaragua" },
                { id: "elseptimo", name: "El Septimo", type: "brand", group: "corporate", country: "costa rica", productLines: ["Sacred Arts", "Emperor", "Zaya", "Culinary Art", "Gilgamesh"], logo: "logos/elseptimo.png" },
                { id: "laaurora", name: "La Aurora", type: "brand", group: "family", country: "dominican", productLines: ["Preferidos", "100 Años", "Family Reserve", "León Jimenes", "ADN Dominicano"], logo: "logos/laaurora.svg" },
                { id: "mayflower", name: "Mayflower Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["Dawn", "Dusk", "Dream"], logo: "logos/mayflower.png" },
                { id: "karenberger", name: "Karen Berger Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["Don Kiki Platinum", "K by Karen Berger Habano", "K by Karen Berger Maduro", "Ixtelli", "Halftime"], logo: "logos/karenberger.jpeg" },
                { id: "karenbergerperson", name: "Karen Berger", type: "person", group: "family", country: "nicaragua", photo: "logos/karenbergerprofile.png" },
                { id: "tabacaleraesteli", name: "Tabacalera Estelí", type: "factory", group: "family", country: "nicaragua" },
                { id: "billpaley", name: "Bill Paley", type: "person", group: "family", country: "usa", photo: "logos/billpaley.png" },
                { id: "lapalina", name: "La Palina", type: "brand", group: "family", country: "usa", productLines: ["Goldie", "Mr. Sam", "Classic", "125 Anos", "White Label", "Black Label", "Silver Label", "Family Series Miami", "La Palina 1948"], logo: "logos/lapalina.png" },
                { id: "eltitandebronze", name: "El Titan de Bronze (Miami)", type: "factory", group: "family", country: "usa", logo: "logos/eltitan.jpg" },
                { id: "pdr", name: "PDR Cigars (Dominican Republic)", type: "factory", group: "family", country: "dominican", logo: "logos/pdrcigars.jpg" },
                { id: "noelrojas", name: "Noel Rojas", type: "person", group: "family", country: "usa", photo: "logos/noelrojas.png" },
                { id: "rojas", name: "Rojas Cigars", type: "brand", group: "family", country: "usa", productLines: ["Guayacan", "Havana Nights", "Unfinished Business", "Street Tacos"], logo: "logos/rojas.png" },
                { id: "guayacan", name: "Guayacan", type: "brand", group: "family", country: "nicaragua", logo: "logos/guayacan.png" },
                { id: "neworder", name: "New Order of the Ages", type: "brand", group: "family", country: "nicaragua" },
                { id: "williamventura", name: "Tabacalera William Ventura", type: "factory", group: "family", country: "dominican" },
                { id: "lucianopichardo", name: "Tabacalera Pichardo (Luciano)", type: "factory", group: "family", country: "nicaragua" },
                { id: "nicasueno", name: "Fábrica de Tabacos Nica Sueño", type: "factory", group: "family", country: "nicaragua" },
                { id: "plasenciahonduras", name: "El Paraíso (Plasencia Honduras)", type: "factory", group: "family", country: "honduras" },
                { id: "stgesteli", name: "STG Estelí", type: "factory", group: "corporate", country: "nicaragua" },
                { id: "stgdanli", name: "STG Danlí (HATSA)", type: "factory", group: "corporate", country: "honduras" },
                { id: "lacorona", name: "La Corona Factory", type: "factory", group: "family", country: "nicaragua" },
                { id: "rojasfactory", name: "Tabacalera New Order (Rojas)", type: "factory", group: "family", country: "nicaragua" },
                { id: "raicescubanas", name: "Raíces Cubanas", type: "factory", group: "family", country: "nicaragua" },
                { id: "laaurorafactory", name: "La Aurora Cigar Factory", type: "factory", group: "family", country: "dominican" },
                { id: "elreyhabanos", name: "El Rey de los Habanos (Miami)", type: "factory", group: "family", country: "usa" },
                { id: "lacarrillo", name: "Casa Carrillo Factory (La Alianza)", type: "factory", group: "family", country: "dominican", logo: "logos/casacarillo.png" },
                { id: "casacarrillo", name: "Casa Carrillo", type: "company", group: "family", country: "usa", productLines: ["Pledge", "Encore", "La Historia", "Allegiance", "Endure", "Deep Blue", "Essence", "INCH", "New Wave Connecticut"], logo: "logos/casacarillo.png" },
                { id: "ernestoperezcarrillo", name: "Ernesto Perez-Carrillo", type: "person", group: "family", country: "usa", photo: "logos/ernestoperezcarillo.png" },
                { id: "laisla", name: "Tabacalera La Isla", type: "factory", group: "family", country: "dominican" },
                { id: "caoamerican", name: "CAO American Caribbean", type: "factory", group: "corporate", country: "nicaragua" },
                { id: "costaricatabacos", name: "Tabacos de Costa Rica", type: "factory", group: "family", country: "costa rica", logo: "logos/tabacosdecostarica.png" },
                { id: "ovejanegra", name: "Oveja Negra (Lanuza)", type: "factory", group: "family", country: "nicaragua" },
                { id: "lanuzafactory", name: "Lanuza Cigar Factory", type: "factory", group: "family", country: "nicaragua" },
                { id: "laflordecopan", name: "La Flor de Copán", type: "factory", group: "family", country: "honduras" },
                { id: "gurkha", name: "Gurkha", type: "brand", group: "corporate", country: "dominican", productLines: ["Classic", "Ghost", "Royal Courtesan", "Heritage"] },
                { id: "caldwell", name: "Caldwell Cigars", type: "brand", group: "family", country: "dominican", productLines: ["Blind Man's Bluff", "Long Live the King", "Lost & Found", "Eastern Standard"], logo: "logos/caldwell.png" },
                { id: "crownedheads", name: "Crowned Heads", type: "brand", group: "family", country: "dominican", productLines: ["Jericho Hill", "Four Kicks", "La Imperiosa", "Mule Kick"], logo: "logos/crownedheads.webp" },
                { id: "southerndraw", name: "Southern Draw", type: "brand", group: "family", country: "dominican", productLines: ["Rose of Sharon", "Kudzu", "Jacob's Ladder", "Firethorn"], logo: "logos/southerndraw.webp" },
                { id: "kristoff", name: "Kristoff", type: "brand", group: "family", country: "dominican", productLines: ["Original Maduro", "GC Signature", "Shiro", "Kristania"], logo: "logos/kristoff.webp" },
                { id: "montecristonc", name: "Montecristo (NC)", type: "brand", group: "corporate", country: "nicaragua" },
                { id: "ryjnc", name: "Romeo y Julieta (NC)", type: "brand", group: "corporate", country: "nicaragua" },
                { id: "trinidadespiritu", name: "Trinidad Espiritu", type: "brand", group: "corporate", country: "nicaragua", productLines: ["Series No. 1", "Series No. 2", "Series No. 3", "Miami Edition"], logo: "logos/trinidad.png" },
                { id: "cain", name: "Cain", type: "brand", group: "corporate", country: "nicaragua", productLines: ["Serie F", "550", "Black", "Habano", "Maduro", "Connecticut CT", "Daytona"], logo: "logos/cain.webp" },
                { id: "nub", name: "NUB", type: "brand", group: "corporate", country: "nicaragua", productLines: ["Connecticut", "Cameroon", "Habano", "Maduro", "Dub", "Nuance", "Cain NUB"], logo: "logos/nub.png" },
                { id: "altadis", name: "Altadis U.S.A.", type: "company", group: "corporate", country: "usa", logo: "logos/altadis.png" },
                { id: "fratello", name: "Fratello", type: "brand", group: "family", country: "nicaragua", productLines: ["Classico", "Navetta", "Bianco", "Arlequin"] },
                { id: "padilla", name: "Padilla Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["La Perla Habana", "Miami", "Golden Age", "Cazadores"], logo: "logos/padilla.jpg" },
                { id: "ozgener", name: "Ozgener Family Cigars", type: "brand", group: "family", country: "nicaragua", productLines: ["Bosphorus", "Aramas", "Cypher", "Pi"] },
                { id: "jassumkral", name: "Jas Sum Kral", type: "brand", group: "family", country: "nicaragua", productLines: ["Red Knight", "La Bomba", "Fenix", "Kral"], logo: "logos/jassumkral.png" },
                { id: "stolenthrone", name: "Stolen Throne", type: "brand", group: "family", country: "nicaragua" },
                { id: "deadwood", name: "Deadwood", type: "brand", group: "family", country: "nicaragua", productLines: ["Fat Bottom Betty", "Sweet Jane", "Yummy Bitches"] },
                { id: "leafbyoscar", name: "Leaf by Oscar", type: "brand", group: "family", country: "honduras", productLines: ["Corojo", "Maduro", "Connecticut", "Sumatra"], logo: "logos/leafbyoscar.webp" },
                { id: "oscarvalladares", name: "Oscar Valladares", type: "brand", group: "family", country: "honduras", productLines: ["Super Fly", "2012", "The Oscar", "Ciserón"], logo: "logos/oscarvalladares.png" },
                { id: "islandjim", name: "Island Jim", type: "brand", group: "family", country: "honduras", productLines: ["No. 2", "Connecticut No. 2", "Barber Pole"], logo: "logos/islandjim.webp" },
                { id: "jimrobinson", name: "\"Island Jim\" Robinson", type: "person", group: "family", country: "usa", photo: "logos/jimrobinson.png" },
                { id: "nicholassyris", name: "Nicholas Syris", type: "person", group: "family", country: "usa", photo: "logos/nicholassyris.jpg" },
                { id: "lhpremium", name: "LH Premium Cigars", type: "brand", group: "family", country: "costa rica", productLines: ["Claro", "Colorado", "Maduro", "Nick", "Nikos", "Nicolas"], logo: "logos/lhpremium.png" },
                { id: "nickandjim", name: "Nick & Jim", type: "brand", group: "family", country: "costa rica", productLines: ["P.B.E.", "Toro"], logo: "logos/nickandjim.png" },
                { id: "lampert", name: "Lampert", type: "brand", group: "family", country: "costa rica", productLines: ["Oro Line", "Ocean Breeze", "Baba Yaga"], logo: "logos/lampert.png" },
                { id: "casdagli", name: "Casdagli", type: "brand", group: "family", country: "costa rica", productLines: ["Villa Casdagli", "Pigasus", "Edición Limitada"], logo: "logos/casdagli.webp" },
                { id: "vegassantiago", name: "Vegas de Santiago", type: "brand", group: "family", country: "costa rica", productLines: ["White Label", "Classic", "Reserva"], logo: "logos/vegasdesantiago.png" },
                { id: "selectedtobacco", name: "Selected Tobacco S.A.", type: "company", group: "family", country: "costa rica", logo: "logos/selectedtobacco.png" },
                { id: "nelsonalfonso", name: "Nelson Alfonso", type: "person", group: "family", country: "costa rica", photo: "logos/nelsonalfonso.png" },
                { id: "attabey", name: "Atabey", type: "brand", group: "boutique", country: "costa rica", productLines: ["Ritos", "Delirios", "Black", "Goddess"], logo: "logos/atabey.png" },
                { id: "byron", name: "Byron", type: "brand", group: "boutique", country: "costa rica", productLines: ["Poetry", "Epicure", "Mesoindic", "Humedor Selection"], logo: "logos/byron.png" },
            ],
            links: [
                { source: "myfather", target: "pepin", type: "founded by" },
                { source: "pepin", target: "tatuaje", type: "manufactures for" },
                { source: "myfather", target: "tatuaje", type: "shared factory roots" },
                { source: "espinosa", target: "erikespinosa", type: "founded by" },
                { source: "espinosa", target: "lazona", type: "opened factory" },
                { source: "lazona", target: "laranja", type: "manufactures" },
                { source: "lazona", target: "espinosahabano", type: "manufactures" },
                { source: "lazona", target: "crema", type: "manufactures" },
                { source: "laranja", target: "espinosa", type: "brand of" },
                { source: "espinosahabano", target: "espinosa", type: "brand of" },
                { source: "crema", target: "espinosa", type: "brand of" },
                { source: "knucklesandwich", target: "espinosa", type: "collaboration / produced under" },
                { source: "knucklesandwich", target: "erikespinosa", type: "collaboration with" },
                { source: "knucklesandwich", target: "guyfieri", type: "co-branded with" },
                { source: "knucklesandwich", target: "sanlotano", type: "manufactured at" },
                { source: "knucklesandwich", target: "ajfernandez", type: "produced by" },
                { source: "eobrands", target: "erikespinosa", type: "co-founded by" },
                { source: "eobrands", target: "eddieortega", type: "co-founded by" },
                { source: "sixzeroone", target: "eobrands", type: "originated at" },
                { source: "murcielago", target: "eobrands", type: "originated at" },
                { source: "sixzeroone", target: "espinosa", type: "brand of" },
                { source: "murcielago", target: "espinosa", type: "brand of" },
                { source: "sixzeroone", target: "ajfernandez", type: "manufactured by" },
                { source: "murcielago", target: "ajfernandez", type: "manufactured by" },
                { source: "ajfernandez", target: "sanlotano", type: "operates" },
                { source: "padron", target: "joseopadron", type: "founded by" },
                { source: "padron", target: "tabacoscubanica", type: "manufactures at" },
                { source: "padron", target: "jorgepadron", type: "family leadership" },
                { source: "padron", target: "orlandopadron", type: "family leadership" },
                { source: "padron1964", target: "padron", type: "series of" },
                { source: "padron1926", target: "padron", type: "series of" },
                { source: "tabacoscubanica", target: "padron1964", type: "manufactures" },
                { source: "tabacoscubanica", target: "padron1926", type: "manufactures" },
                { source: "davidoff", target: "oettinger", type: "owned by" },
                { source: "avo", target: "oettinger", type: "owned by" },
                { source: "griffins", target: "oettinger", type: "owned by" },
                { source: "davidoff", target: "tabadom", type: "manufactures at" },
                { source: "avo", target: "tabadom", type: "manufactures at" },
                { source: "griffins", target: "tabadom", type: "manufactures at" },
                { source: "tabadom", target: "oettinger", type: "subsidiary of" },
                { source: "arturo", target: "tabafuente", type: "manufactures at" },
                { source: "opusx", target: "arturo", type: "flagship line of" },
                { source: "diamondcrown", target: "jcnewman", type: "brand of" },
                { source: "diamondcrown", target: "tabafuente", type: "handmade at" },
                { source: "jcnewman", target: "arturo", type: "longtime partnership" },
                { source: "generalcigar", target: "stg", type: "owned by" },
                { source: "forged", target: "stg", type: "owned by" },
                { source: "macanudo", target: "generalcigar", type: "sold by" },
                { source: "cao", target: "generalcigar", type: "sold by" },
                { source: "partagas_nc", target: "generalcigar", type: "sold by" },
                { source: "cohiba_nc", target: "forged", type: "sold by" },
                { source: "punch_nc", target: "forged", type: "sold by" },
                { source: "plasencia", target: "nestorplasencia", type: "founded by / family leadership" },
                { source: "plasencia", target: "nestorandres", type: "family leadership" },
                { source: "plasencia", target: "plasenciaesteli", type: "operates" },
                { source: "stg", target: "plasencia", type: "minority stake (General Cigar)" },
                { source: "rockypatel", target: "nishpatel", type: "family leadership" },
                { source: "rockypatel", target: "tavicusa", type: "owns" },
                { source: "rockypatel", target: "plasencia", type: "long-term manufacturing partnership (Honduras)" },
                { source: "rockypatel", target: "plasenciaesteli", type: "contract production" },
                { source: "drewestate", target: "jonathandrew", type: "founded by" },
                { source: "drewestate", target: "lagranfabrica", type: "operates" },
                { source: "swisher", target: "drewestate", type: "owns (acquired 2014)" },
                { source: "cle", target: "christianeiroa", type: "founded by" },
                { source: "cle", target: "eiroadanli", type: "operates" },
                { source: "eiroafamily", target: "christianeiroa", type: "family" },
                { source: "eiroafamily", target: "eiroadanli", type: "operates" },
                { source: "aganorsa", target: "maxfernandez", type: "family leadership" },
                { source: "aganorsa", target: "tabsa", type: "operates" },
                { source: "foundation", target: "nickmelillo", type: "founded by" },
                { source: "foundation", target: "myfather", type: "production partner (Wise Man)" },
                { source: "foundation", target: "ajfernandez", type: "production partner (Tabernacle, Olmec)" },
                { source: "foundation", target: "sanlotano", type: "production at" },
                { source: "alecbradley", target: "stg", type: "owned by (acquired 2023)" },
                { source: "alecbradley", target: "forged", type: "sold by" },
                { source: "room101", target: "stg", type: "owned by (acquired 2022)" },
                { source: "room101", target: "generalcigar", type: "sold by" },
                { source: "warped", target: "kylegellis", type: "founded by" },
                { source: "warped", target: "tabsa", type: "historical production (Aganorsa)" },
                { source: "warped", target: "nacsa", type: "major production partner (2024-2026)" },
                { source: "kylegellis", target: "nacsa", type: "close oversight" },
                { source: "oliva", target: "fredvandermarliere", type: "owned by (Vandermarliere family)" },
                { source: "oliva", target: "tabolisa", type: "operates" },
                { source: "oliva", target: "aganorsa", type: "major tobacco supplier" },
                { source: "perdomo", target: "nickperdomo", type: "founded by / family leadership" },
                { source: "perdomo", target: "perdomofactory", type: "operates (El Monstro)" },
                { source: "joya", target: "joyafactory", type: "produced at" },
                { source: "joyafactory", target: "alejandromartinez", type: "family ownership" },
                { source: "sobremesa", target: "joyafactory", type: "produced at (Dunbarton)" },
                { source: "dunbarton", target: "stevesaka", type: "founded by" },
                { source: "dunbarton", target: "sobremesa", type: "core brand" },
                { source: "joyafactory", target: "dunbarton", type: "contract production" },
                { source: "illusione", target: "diongiolito", type: "founded by" },
                { source: "illusione", target: "tabsa", type: "long-term production (Aganorsa)" },
                { source: "illusione", target: "sanlotano", type: "some production" },
                { source: "viaje", target: "andrefarkas", type: "founded by" },
                { source: "viaje", target: "tabsa", type: "frequent production partner" },
                { source: "viaje", target: "joyafactory", type: "production at Joya" },
                { source: "hvc", target: "reinierlorenzo", type: "founded by" },
                { source: "hvc", target: "hvcfactory", type: "operates own factory" },
                { source: "joyafactory", target: "drewestate", type: "historical contract production (MUWAT era)" },
                { source: "joyafactory", target: "warped", type: "occasional production" },
                { source: "perdomofactory", target: "perdomo", type: "core production for all Perdomo lines" },
                { source: "tabolisa", target: "oliva", type: "primary rolling for Serie V / Melanio / NUb" },
                { source: "sobremesa", target: "joyafactory", type: "primary production location" },
                { source: "dunbarton", target: "nacsa", type: "some Muestra de Saka / Mi Querida production" },
                { source: "perdomo", target: "stg", type: "occasional leaf / industry relationship" },
                { source: "hvc", target: "tabsa", type: "early production before own factory" },
                { source: "westtampa", target: "rickrodriguez", type: "founded by" },
                { source: "rickrodriguez", target: "generalcigar", type: "longtime blender (CAO)" },
                { source: "rickrodriguez", target: "cao", type: "longtime blender and ambassador" },
                { source: "westtampa", target: "garmendia", type: "manufactured at" },
                { source: "westtampa", target: "nacsa", type: "some production at" },
                { source: "belladamacigars", target: "chantelleavitt", type: "founded by" },
                { source: "belladamacigars", target: "tabacaleraaragon", type: "manufactured at" },
                { source: "camacho", target: "davidoff", type: "owned by (Davidoff group)" },
                { source: "camacho", target: "oettinger", type: "owned by (Oettinger Davidoff)" },
                { source: "camacho", target: "christianeiroa", type: "historical ownership (Eiroa family)" },
                { source: "camacho", target: "cle", type: "historical roots (Christian Eiroa)" },
                { source: "zino", target: "davidoff", type: "owned by (Davidoff group)" },
                { source: "zino", target: "oettinger", type: "owned by (Oettinger Davidoff)" },
                { source: "laaromadecuba", target: "myfather", type: "produced at My Father factory" },
                { source: "laaromadecuba", target: "ashton", type: "owned by (Levin family / Ashton)" },
                { source: "sancristobal", target: "myfather", type: "produced at My Father factory" },
                { source: "sancristobal", target: "ashton", type: "owned by (Levin family / Ashton)" },
                { source: "sancristobal", target: "tatuaje", type: "family connection (Pete Johnson & Janny Garcia)" },
                { source: "ashton", target: "arturo", type: "produced at Arturo Fuente factory" },
                { source: "ashton", target: "tabafuente", type: "manufactured at" },
                { source: "lagloriacubana", target: "generalcigar", type: "owned by (General Cigar / STG)" },
                { source: "lagloriacubana", target: "stg", type: "owned by" },
                { source: "mayflower", target: "oliva", type: "produced at Oliva factory" },
                { source: "mayflower", target: "tabolisa", type: "manufactured at" },
                { source: "karenberger", target: "karenbergerperson", type: "founded and led by" },
                { source: "karenberger", target: "tabacaleraesteli", type: "manufactured at (own factory)" },
                { source: "lapalina", target: "billpaley", type: "revived by" },
                { source: "lapalina", target: "eltitandebronze", type: "Goldie produced at" },
                { source: "lapalina", target: "ajfernandez", type: "some production with AJ Fernandez" },
                { source: "lapalina", target: "pdr", type: "some production at PDR" },
                { source: "rojas", target: "noelrojas", type: "founded by" },
                { source: "guayacan", target: "rojas", type: "brand of" },
                { source: "neworder", target: "rojas", type: "brand of / originated as" },
                { source: "guayacan", target: "ajfernandez", type: "rolled at" },
                { source: "neworder", target: "ajfernandez", type: "rolled at" },
                { source: "rojas", target: "ajfernandez", type: "contract manufactured at" },
                { source: "definition", target: "lucianopichardo", type: "manufactured at" },
                { source: "laaurora", target: "laaurorafactory", type: "manufactured at" },
                { source: "lure", target: "ovejanegra", type: "manufactured at" },
                { source: "dunbarton", target: "lazona", type: "contract production" },
                { source: "dunbarton", target: "ajfernandez", type: "contract production" },
                { source: "guayacan", target: "myfather", type: "Reserve line produced at" },
                { source: "foundation", target: "joyafactory", type: "production at" },
                { source: "murcielago", target: "plasencia", type: "contract production" },
                { source: "espinosa", target: "plasencia", type: "contract production" },
                { source: "lagranfabrica", target: "macanudo", type: "manufactures" },
                { source: "lagranfabrica", target: "cohiba_nc", type: "manufactures" },
                { source: "lagranfabrica", target: "punch_nc", type: "manufactures" },
                { source: "lagranfabrica", target: "lagloriacubana", type: "manufactures" },
                { source: "room101", target: "eiroadanli", type: "Honduras production at" },
                { source: "room101", target: "stgdanli", type: "Honduras production at" },
                { source: "tatuaje", target: "elreyhabanos", type: "originated at" },
                { source: "tatuaje", target: "plasenciahonduras", type: "contract production" },
                { source: "lapalina", target: "tabsa", type: "production at" },
                { source: "lapalina", target: "williamventura", type: "production at" },
                { source: "lapalina", target: "caoamerican", type: "production at" },
                { source: "lapalina", target: "plasenciahonduras", type: "production at" },
                { source: "stgesteli", target: "stg", type: "operated by" },
                { source: "stgdanli", target: "stg", type: "operated by" },
                { source: "plasenciahonduras", target: "plasencia", type: "operated by" },
                { source: "laaurorafactory", target: "laaurora", type: "primary factory for" },
                { source: "elreyhabanos", target: "pepin", type: "historic García factory" },
                { source: "rojasfactory", target: "noelrojas", type: "associated with" },
                { source: "lazona", target: "murcielago", type: "manufactures" },
                { source: "gurkha", target: "williamventura", type: "manufactured at" },
                { source: "gurkha", target: "lacarrillo", type: "manufactured at" },
                { source: "casacarrillo", target: "ernestoperezcarrillo", type: "founded by" },
                { source: "casacarrillo", target: "lacarrillo", type: "operates" },
                { source: "casacarrillo", target: "kristoff", type: "family portfolio" },
                { source: "ernestoperezcarrillo", target: "casacarrillo", type: "founded" },
                { source: "ernestoperezcarrillo", target: "lagloriacubana", type: "originated blend (sold 1999)" },
                { source: "ernestoperezcarrillo", target: "generalcigar", type: "formerly with (until 2009)" },
                { source: "lacarrillo", target: "casacarrillo", type: "operated by" },
                { source: "lacarrillo", target: "gurkha", type: "manufactures" },
                { source: "lacarrillo", target: "casdagli", type: "contract manufactures" },
                { source: "crownedheads", target: "lacarrillo", type: "some production at" },
                { source: "caldwell", target: "lacarrillo", type: "collaboration production" },
                { source: "kristoff", target: "casacarrillo", type: "Perez-Carrillo family" },
                { source: "caldwell", target: "pdr", type: "manufactured at" },
                { source: "caldwell", target: "nicasueno", type: "manufactured at" },
                { source: "caldwell", target: "williamventura", type: "manufactured at" },
                { source: "crownedheads", target: "myfather", type: "manufactured at" },
                { source: "crownedheads", target: "nacsa", type: "historical production at" },
                { source: "southerndraw", target: "plasenciahonduras", type: "manufactured at" },
                { source: "kristoff", target: "williamventura", type: "manufactured at" },
                { source: "montecristonc", target: "stgesteli", type: "manufactured at" },
                { source: "montecristonc", target: "stg", type: "owned by" },
                { source: "montecristonc", target: "generalcigar", type: "sold by" },
                { source: "ryjnc", target: "stgesteli", type: "manufactured at" },
                { source: "ryjnc", target: "plasencia", type: "contract production" },
                { source: "ryjnc", target: "stg", type: "owned by" },
                { source: "ryjnc", target: "generalcigar", type: "sold by" },
                { source: "fratello", target: "lazona", type: "manufactured at" },
                { source: "fratello", target: "laisla", type: "manufactured at" },
                { source: "padilla", target: "tabsa", type: "manufactured at" },
                { source: "padilla", target: "plasenciahonduras", type: "manufactured at" },
                { source: "padilla", target: "stgesteli", type: "manufactured at" },
                { source: "ozgener", target: "lacorona", type: "manufactured at" },
                { source: "jassumkral", target: "myfather", type: "manufactured at" },
                { source: "stolenthrone", target: "rojasfactory", type: "manufactured at" },
                { source: "deadwood", target: "raicescubanas", type: "manufactured at" },
                { source: "deadwood", target: "drewestate", type: "brand of" },
                { source: "leafbyoscar", target: "laflordecopan", type: "manufactured at" },
                { source: "oscarvalladares", target: "laflordecopan", type: "related production" },
                { source: "plasenciaesteli", target: "murcielago", type: "manufactures" },
                { source: "knucklesandwich", target: "plasencia", type: "contract production" },
                { source: "dunbarton", target: "sanlotano", type: "production at" },
                { source: "guayacan", target: "sanlotano", type: "rolled at" },
                { source: "neworder", target: "rojasfactory", type: "originated at" },
                { source: "rojas", target: "rojasfactory", type: "associated factory" },
                { source: "hvc", target: "joyafactory", type: "contract production" },
                { source: "illusione", target: "joyafactory", type: "production at" },
                { source: "viaje", target: "lazona", type: "contract production" },
                { source: "fratello", target: "lazona", type: "contract production" },
                { source: "hvc", target: "tabsa", type: "early production at" },
                { source: "padilla", target: "tabsa", type: "contract production" },
                { source: "jassumkral", target: "myfather", type: "contract production" },
                { source: "stgesteli", target: "montecristonc", type: "manufactures" },
                { source: "stgesteli", target: "ryjnc", type: "manufactures" },
                { source: "stgesteli", target: "padilla", type: "manufactures" },
                { source: "stgesteli", target: "room101", type: "manufactures" },
                { source: "stgesteli", target: "southerndraw", type: "manufactures" },
                { source: "stgesteli", target: "foundation", type: "manufactures" },
                { source: "stgesteli", target: "hvc", type: "manufactures" },
                { source: "stgesteli", target: "cohiba_nc", type: "manufactures" },
                { source: "stgesteli", target: "macanudo", type: "manufactures" },
                { source: "stgesteli", target: "punch_nc", type: "manufactures" },
                { source: "stgesteli", target: "lagloriacubana", type: "manufactures" },
                { source: "caoamerican", target: "cao", type: "related facility" },
                { source: "caoamerican", target: "lapalina", type: "manufactures" },
                { source: "raicescubanas", target: "deadwood", type: "manufactures" },
                { source: "drewestate", target: "deadwood", type: "owns line" },
                { source: "williamventura", target: "viaje", type: "manufactures" },
                { source: "williamventura", target: "kristoff", type: "manufactures" },
                { source: "williamventura", target: "caldwell", type: "manufactures" },
                { source: "williamventura", target: "lapalina", type: "manufactures" },
                { source: "laisla", target: "fratello", type: "manufactures" },
                { source: "nicasueno", target: "caldwell", type: "manufactures" },
                { source: "lacorona", target: "ozgener", type: "manufactures" },
                { source: "lucianopichardo", target: "definition", type: "manufactures" },
                { source: "ovejanegra", target: "lure", type: "manufactures" },
                { source: "lanuzafactory", target: "ovejanegra", type: "related facility" },
                { source: "plasenciahonduras", target: "southerndraw", type: "manufactures" },
                { source: "plasenciahonduras", target: "padilla", type: "manufactures" },
                { source: "plasenciahonduras", target: "tatuaje", type: "manufactures" },
                { source: "plasenciahonduras", target: "lapalina", type: "manufactures" },
                { source: "stgdanli", target: "room101", type: "manufactures" },
                { source: "stgdanli", target: "leafbyoscar", type: "manufactures" },
                { source: "stgdanli", target: "zino", type: "manufactures" },
                { source: "laflordecopan", target: "leafbyoscar", type: "manufactures" },
                { source: "islandjim", target: "jimrobinson", type: "founded by" },
                { source: "jimrobinson", target: "islandjim", type: "created" },
                { source: "jimrobinson", target: "leafbyoscar", type: "created" },
                { source: "leafbyoscar", target: "jimrobinson", type: "created by" },
                { source: "islandjim", target: "laflordecopan", type: "manufactured at" },
                { source: "islandjim", target: "oscarvalladares", type: "rolled by" },
                { source: "islandjim", target: "leafbyoscar", type: "shared factory roots" },
                { source: "oscarvalladares", target: "islandjim", type: "manufactures for" },
                { source: "laflordecopan", target: "islandjim", type: "manufactures" },
                { source: "jimrobinson", target: "oscarvalladares", type: "factory partnership" },
                { source: "jimrobinson", target: "eddieortega", type: "Wild Bunch collaborator" },
                { source: "lhpremium", target: "nicholassyris", type: "founded by" },
                { source: "nicholassyris", target: "lhpremium", type: "founded" },
                { source: "lhpremium", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "lhpremium", type: "manufactures" },
                { source: "nickandjim", target: "nicholassyris", type: "collaboration with" },
                { source: "nickandjim", target: "jimrobinson", type: "co-branded with" },
                { source: "nickandjim", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "nickandjim", type: "manufactures" },
                { source: "nickandjim", target: "lhpremium", type: "Nick line of" },
                { source: "nicholassyris", target: "jimrobinson", type: "collaboration with" },
                { source: "jimrobinson", target: "nicholassyris", type: "collaboration with" },
                { source: "lampert", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "lampert", type: "manufactures" },
                { source: "casdagli", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "casdagli", type: "manufactures" },
                { source: "vegassantiago", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "vegassantiago", type: "manufactures" },
                { source: "attabey", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "attabey", type: "manufactures" },
                { source: "byron", target: "costaricatabacos", type: "manufactured at" },
                { source: "costaricatabacos", target: "byron", type: "manufactures" },
                { source: "attabey", target: "selectedtobacco", type: "brand of" },
                { source: "byron", target: "selectedtobacco", type: "brand of" },
                { source: "selectedtobacco", target: "attabey", type: "owns" },
                { source: "selectedtobacco", target: "byron", type: "owns" },
                { source: "selectedtobacco", target: "nelsonalfonso", type: "founded by" },
                { source: "nelsonalfonso", target: "selectedtobacco", type: "founded" },
                { source: "trinidadespiritu", target: "sanlotano", type: "manufactured at" },
                { source: "trinidadespiritu", target: "ajfernandez", type: "collaboration with" },
                { source: "trinidadespiritu", target: "altadis", type: "distributed by" },
                { source: "altadis", target: "trinidadespiritu", type: "owns / distributes" },
                { source: "sanlotano", target: "trinidadespiritu", type: "manufactures" },
                { source: "ajfernandez", target: "trinidadespiritu", type: "collaboration blends" },
                { source: "cain", target: "oliva", type: "brand of (Oliva Cigar Co.)" },
                { source: "cain", target: "tabolisa", type: "manufactured at" },
                { source: "oliva", target: "cain", type: "owns / portfolio" },
                { source: "tabolisa", target: "cain", type: "manufactures" },
                { source: "nub", target: "oliva", type: "brand of (Oliva Cigar Co.)" },
                { source: "nub", target: "tabolisa", type: "manufactured at" },
                { source: "nub", target: "cain", type: "sibling brand (Studio Tobac)" },
                { source: "oliva", target: "nub", type: "owns / portfolio" },
                { source: "tabolisa", target: "nub", type: "manufactures" },
                { source: "cain", target: "nub", type: "sibling brand (Cain NUB crossover)" },
                { source: "domain", target: "daniellance", type: "co-founded by" },
                { source: "domain", target: "estebandisla", type: "co-founded by" },
                { source: "daniellance", target: "domain", type: "co-founded" },
                { source: "estebandisla", target: "domain", type: "co-founded" },
                { source: "daniellance", target: "estebandisla", type: "co-founder with" },
                { source: "estebandisla", target: "daniellance", type: "co-founder with" },
                { source: "domain", target: "familiadisla", type: "manufactured at" },
                { source: "familiadisla", target: "domain", type: "manufactures" },
                { source: "estebandisla", target: "familiadisla", type: "operates" },
                { source: "familiadisla", target: "estebandisla", type: "operated by" },
                { source: "daniellance", target: "familiadisla", type: "operates" },
                { source: "familiadisla", target: "daniellance", type: "operated by" },
                { source: "estebandisla", target: "nicasueno", type: "former production at (10+ years)" },
                { source: "nicasueno", target: "estebandisla", type: "historical master blender at" },
                { source: "estebandisla", target: "stgesteli", type: "historical blending at" },
                { source: "stgesteli", target: "estebandisla", type: "historical master blender at" },
                { source: "estebandisla", target: "cao", type: "historical blends for" },
                { source: "estebandisla", target: "alecbradley", type: "historical blends for" },
            ]
        };
