/**
 * Official external URLs for Cigar Nexus nodes (SEO cross-links on node pages).
 * Loaded by scripts/generate-node-pages.js — not used on the interactive map drawer yet.
 *
 * Future: add per-node social profiles, e.g.
 *   social: { instagram: "https://...", x: "https://..." }
 */
var nodeWebsites = {
  ajfernandez: { website: "https://ajfcigars.com" },
  aganorsa: { website: "https://www.aganorsaleaf.com" },
  alecbradley: { website: "https://alecbradley.com" },
  alejandromartinez: { website: "https://joyacigars.com", websiteLabel: "Joya de Nicaragua" },
  andrefarkas: { website: "https://www.viajecigars.com", websiteLabel: "Viaje Cigars" },
  arturo: { website: "https://arturofuente.com" },
  ashton: { website: "https://www.ashtoncigars.com" },
  avo: { website: "https://us.davidoffgeneva.com", websiteLabel: "AVO (Davidoff)" },
  belladamacigars: { website: "https://belladamacigars.com" },
  billpaley: { website: "https://lapalinacigars.com", websiteLabel: "La Palina" },
  camacho: { website: "https://us.davidoffgeneva.com/discover/camacho", websiteLabel: "Camacho (Davidoff)" },
  cao: { website: "https://caocigars.com" },
  chantelleavitt: { website: "https://belladamacigars.com", websiteLabel: "Bella Dama Cigars" },
  christianeiroa: { website: "https://clecigars.com", websiteLabel: "C.L.E. Cigar Company" },
  cle: { website: "https://clecigars.com" },
  cohiba_nc: { website: "https://www.cohiba.com", websiteLabel: "Cohiba (US)" },
  crema: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  davidoff: { website: "https://www.davidoff.com" },
  definition: { website: "https://definitioncigars.com" },
  diamondcrown: { website: "https://jcnewman.com", websiteLabel: "J.C. Newman / Diamond Crown" },
  diongiolito: { website: "https://illusionecigars.com", websiteLabel: "Illusione Cigars" },
  domain: { website: "https://domaincigars.com" },
  drewestate: { website: "https://drewestate.com" },
  dunbarton: { website: "https://www.dunbartoncigars.com" },
  eddieortega: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  eiroadanli: { website: "https://clecigars.com", websiteLabel: "C.L.E. Factory (Danlí)" },
  eiroafamily: { website: "https://www.jretobacco.com", websiteLabel: "JRE Tobacco / Aladino" },
  eobrands: { website: "https://www.eobrands.com" },
  elseptimo: { website: "https://el-septimo.com" },
  erikespinosa: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  espinosa: { website: "https://espinosacigars.com" },
  espinosahabano: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  eltitandebronze: { website: "https://eltitancigars.com", websiteLabel: "El Titan de Bronze" },
  forged: { website: "https://forgedcigarco.com" },
  foundation: { website: "https://foundationcigarcompany.com" },
  fredvandermarliere: { website: "https://olivacigar.com", websiteLabel: "Oliva Cigar Co." },
  garmendia: { website: "https://garmendiacigars.com" },
  generalcigar: { website: "https://www.generalcigar.com" },
  griffins: { website: "https://us.davidoffgeneva.com", websiteLabel: "The Griffin's (Davidoff)" },
  guayacan: { website: "https://www.rojascigars.com", websiteLabel: "Rojas Cigars" },
  guyfieri: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  hvc: { website: "https://hvccigars.com" },
  hvcfactory: { website: "https://hvccigars.com", websiteLabel: "HVC Cigars" },
  illusione: { website: "https://illusionecigars.com" },
  jcnewman: { website: "https://jcnewman.com" },
  jorgepadron: { website: "https://padron.com", websiteLabel: "Padrón" },
  joseopadron: { website: "https://padron.com", websiteLabel: "Padrón" },
  jonathandrew: { website: "https://drewestate.com", websiteLabel: "Drew Estate" },
  joya: { website: "https://joyacigars.com" },
  joyafactory: { website: "https://joyacigars.com", websiteLabel: "Joya de Nicaragua" },
  karenberger: { website: "https://karenbergercigars.com" },
  karenbergerperson: { website: "https://karenbergercigars.com", websiteLabel: "Karen Berger Cigars" },
  knucklesandwich: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  kylegellis: { website: "https://www.warpedcigars.com", websiteLabel: "Warped Cigars" },
  lagloriacubana: { website: "https://lagloriacubana.com" },
  lagranfabrica: { website: "https://drewestate.com", websiteLabel: "Drew Estate" },
  laaromadecuba: { website: "https://laaromadecuba.com" },
  laaurora: { website: "https://www.laaurora.com.do" },
  lapalina: { website: "https://lapalinacigars.com" },
  laranja: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  lazona: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  lure: { website: "https://lurecigars.com" },
  macanudo: { website: "https://macanudo.com" },
  maxfernandez: { website: "https://www.aganorsaleaf.com", websiteLabel: "Aganorsa Leaf" },
  mayflower: { website: "https://mayflowercigars.com" },
  murcielago: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  myfather: { website: "https://myfathercigars.com" },
  nestorandres: { website: "https://plasenciacigars.com", websiteLabel: "Plasencia Cigars" },
  nestorplasencia: { website: "https://plasenciacigars.com", websiteLabel: "Plasencia Cigars" },
  neworder: { website: "https://www.rojascigars.com", websiteLabel: "Rojas Cigars" },
  nickmelillo: { website: "https://foundationcigarcompany.com", websiteLabel: "Foundation Cigar Company" },
  nickperdomo: { website: "https://perdomocigars.com", websiteLabel: "Perdomo Cigars" },
  nishpatel: { website: "https://www.rockypatel.com", websiteLabel: "Rocky Patel" },
  noelrojas: { website: "https://www.rojascigars.com", websiteLabel: "Rojas Cigars" },
  oliva: { website: "https://olivacigar.com" },
  oettinger: { website: "https://www.oettingerdavidoff.com" },
  opusx: { website: "https://arturofuente.com", websiteLabel: "Arturo Fuente" },
  orlandopadron: { website: "https://padron.com", websiteLabel: "Padrón" },
  padron: { website: "https://padron.com" },
  padron1926: { website: "https://padron.com", websiteLabel: "Padrón" },
  padron1964: { website: "https://padron.com", websiteLabel: "Padrón" },
  partagas_nc: { website: "https://www.partagas.com", websiteLabel: "Partagás (US)" },
  pdr: { website: "https://pdrcigars.com" },
  pepin: { website: "https://myfathercigars.com", websiteLabel: "My Father Cigars" },
  perdomo: { website: "https://perdomocigars.com" },
  perdomofactory: { website: "https://perdomocigars.com", websiteLabel: "Perdomo Cigars" },
  plasencia: { website: "https://plasenciacigars.com" },
  plasenciaesteli: { website: "https://plasenciacigars.com", websiteLabel: "Plasencia Cigars" },
  punch_nc: { website: "https://punchcigars.com", websiteLabel: "Punch (US)" },
  reinierlorenzo: { website: "https://hvccigars.com", websiteLabel: "HVC Cigars" },
  rickrodriguez: { website: "https://www.westtampatobacco.com", websiteLabel: "West Tampa Tobacco Co." },
  rockypatel: { website: "https://www.rockypatel.com" },
  rojas: { website: "https://www.rojascigars.com" },
  room101: { website: "https://room101cigars.com" },
  sanlotano: { website: "https://ajfcigars.com", websiteLabel: "A.J. Fernandez" },
  sancristobal: { website: "https://www.sancristobalcigar.com" },
  sixzeroone: { website: "https://espinosacigars.com", websiteLabel: "Espinosa Premium Cigars" },
  sobremesa: { website: "https://www.dunbartoncigars.com", websiteLabel: "Dunbarton Tobacco & Trust" },
  stevesaka: { website: "https://www.dunbartoncigars.com", websiteLabel: "Dunbarton Tobacco & Trust" },
  stg: { website: "https://www.st-group.com", websiteLabel: "Scandinavian Tobacco Group" },
  swisher: { website: "https://swisher.com" },
  tabacaleraaragon: { website: "https://belladamacigars.com", websiteLabel: "Bella Dama Cigars" },
  tabacaleraesteli: { website: "https://karenbergercigars.com", websiteLabel: "Karen Berger Cigars" },
  tabadom: { website: "https://www.davidoff.com", websiteLabel: "Davidoff" },
  tabafuente: { website: "https://arturofuente.com", websiteLabel: "Arturo Fuente" },
  tabacoscubanica: { website: "https://padron.com", websiteLabel: "Padrón" },
  tabsa: { website: "https://www.aganorsaleaf.com", websiteLabel: "Aganorsa Leaf" },
  tabolisa: { website: "https://olivacigar.com", websiteLabel: "Oliva Cigar Co." },
  tatuaje: { website: "https://tatuajecigars.com" },
  tavicusa: { website: "https://www.rockypatel.com", websiteLabel: "Rocky Patel" },
  viaje: { website: "https://www.viajecigars.com" },
  warped: { website: "https://www.warpedcigars.com" },
  westtampa: { website: "https://www.westtampatobacco.com" },
  zino: { website: "https://us.davidoffgeneva.com", websiteLabel: "Zino (Davidoff)" },

  // P0–P3 factory nodes
  williamventura: { website: "https://www.williamventuracigars.com" },
  lucianopichardo: { website: "https://lucianocigars.com", websiteLabel: "Luciano Cigars" },
  nicasueno: { website: "https://nicasuenocigars.com" },
  plasenciahonduras: { website: "https://plasenciacigars.com", websiteLabel: "Plasencia Cigars" },
  stgesteli: { website: "https://www.st-group.com", websiteLabel: "Scandinavian Tobacco Group" },
  stgdanli: { website: "https://www.st-group.com", websiteLabel: "Scandinavian Tobacco Group" },
  lacorona: { website: "https://ozgenerfamilycigars.com", websiteLabel: "Ozgener Family Cigars" },
  rojasfactory: { website: "https://www.rojascigars.com", websiteLabel: "Rojas Cigars" },
  raicescubanas: { website: "https://drewestate.com", websiteLabel: "Drew Estate" },
  laaurorafactory: { website: "https://www.laaurora.com.do", websiteLabel: "La Aurora" },
  elreyhabanos: { website: "https://myfathercigars.com", websiteLabel: "My Father Cigars (historic Miami origin)" },
  casacarrillo: { website: "https://casacarrillocigars.com" },
  ernestoperezcarrillo: { website: "https://casacarrillocigars.com/about-us/", websiteLabel: "Casa Carrillo" },
  lacarrillo: { website: "https://casacarrillocigars.com/about-us/our-factory/", websiteLabel: "Our Factory" },
  laisla: { website: "https://fratellobycrux.com", websiteLabel: "Fratello / La Isla" },
  caoamerican: { website: "https://caocigars.com", websiteLabel: "CAO" },

  ovejanegra: { website: "https://www.lanuza.com", websiteLabel: "Lanuza Cigars" },
  lanuzafactory: { website: "https://www.lanuza.com", websiteLabel: "Lanuza Cigars" },
  laflordecopan: { website: "https://oscarcigars.com", websiteLabel: "Oscar Valladares" },
  nacsa: { website: "https://www.warpedcigars.com", websiteLabel: "Warped Cigars (NACSA partner)" },

  // P2 brand nodes
  gurkha: { website: "https://gurkhacigars.com" },
  caldwell: { website: "https://caldwellcigars.com" },
  crownedheads: { website: "https://crownedheads.com" },
  southerndraw: { website: "https://southerndrawcigars.com" },
  kristoff: { website: "https://kristoffcigars.com" },
  montecristonc: { website: "https://www.montecristo.com", websiteLabel: "Montecristo (US)" },
  ryjnc: { website: "https://www.romeoyjulieta.com", websiteLabel: "Romeo y Julieta (US)" },
  fratello: { website: "https://fratellobycrux.com" },
  padilla: { website: "https://padillacigars.com" },
  ozgener: { website: "https://ozgenerfamilycigars.com" },
  jassumkral: { website: "https://jassumkral.com" },
  stolenthrone: { website: "https://stolenthronecigars.com" },
  deadwood: { website: "https://drewestate.com", websiteLabel: "Drew Estate (Deadwood)" },
  leafbyoscar: { website: "https://oscarcigars.com", websiteLabel: "Oscar Valladares" },
  oscarvalladares: { website: "https://oscarcigars.com" },
  islandjim: { website: "https://oscartobacco.com", websiteLabel: "Oscar Valladares Tobacco & Co." },
  jimrobinson: { website: "https://www.leafandbean.com/stripdistrict", websiteLabel: "Leaf & Bean Strip District" },
  nicholassyris: { website: "https://lhcigars.com", websiteLabel: "LH Premium Cigars" },
  lhpremium: { website: "https://lhcigars.com" },
  nickandjim: { website: "https://lhcigars.com", websiteLabel: "LH Premium Cigars" },
  lampert: { website: "https://lampertcigars.com" },
  casdagli: { website: "https://casdaglicigars.com" },
  vegassantiago: { website: "https://www.cigars-vegasantiago.biz" },
  attabey: { website: "https://unitedcigargroup.com/atabey/", websiteLabel: "Atabey (United Cigar)" },
  byron: { website: "https://www.2guyscigars.com/selected-tobacco/", websiteLabel: "Byron (Selected Tobacco)" },
  selectedtobacco: { website: "https://www.2guyscigars.com/selected-tobacco/" }
};